### ISSUE TITLE
فراخوانی مجدد کانفیگ بعد از تغییرات 

### ISSUE THREAD

**Issue by esmaielahmadi** [namelesghoul/sing-box-REALITY#1]
سلام 

خدا قوت اقا وقتی تغیییرات ایجاد کردیم چطوری کانفیگ که تغییر رده رو باید فراخوانی کنیم و بهمون نمایش  بده ؟

**Comment by namelesghoul** [comment]
سلام و خسته نباشید . متاسفانه هنوز فرصت نکردم این قضیه رو اضافه کنم . در حال حاضر از اونجایی که فقط پورت و sni تغییر میکنه تنها لازمه که برید داخل کانفیگ v2rayn که از قبل اد کردید و تغییرات رو دستی اضافه کنید . به عنوان مثال اگر داخل اسکریپت اسکریپت پورت رو به 8080 تغییر دادید , در کانفیگی که از قبل داشتید دستی پورت را وارد کنید.
نسخه بعدی این آپشن اضافه میشه

**Comment by deathline94** [comment]
https://github.com/deathline94/sing-REALITY-Box
