### ISSUE TITLE
سپاسگزارم

### ISSUE THREAD

**Issue by ghafari3** [namelesghoul/sing-box-REALITY#2]
درود

نصب کردم و بخوبی کار میکنه

فقط لطف کنید دستورات و چگونگی ایجاد تغییرات در آدرس سرور، حذف اسکریپت و ... را هم در توضیحات درج بفرمایید.

**Comment by namelesghoul** [comment]
به اسکریپت منو اضافه شده برای حذف , تغییرات و نصب مجدد و با انتخاب هر گزینه میتونید به سادگی هرچه تمام تر انجام بدید این کار رو
