### ISSUE TITLE
uninstal

### ISSUE THREAD

**Issue by shahrokh451** [namelesghoul/sing-box-REALITY#3]
uninstal script please

**Comment by namelesghoul** [comment]
اسکریپت را مجدد ران کنید و گزینه 3 رو انتخاب کنید

**Comment by shahrokh451** [comment]
متشکرم



Sent from my Galaxy



-------- Original message --------
From: Nameles Ghoul ***@***.***>
Date: 5/19/23 18:12 (GMT+03:30)
To: namelesghoul/sing-box-REALITY ***@***.***>
Cc: shahrokh451 ***@***.***>, Author ***@***.***>
Subject: Re: [namelesghoul/sing-box-REALITY] uninstal (Issue #3)


اسکریپت را مجدد ران کنید و گزینه 3 رو انتخاب کنید

**Comment by namelesghoul** [comment]
<3

**Comment by shahrokh451** [comment]
لطفا راهنمایی کنید از ایران بدون کردیت کارد با ارز دیجیتال از کجا سرور بگیریم که ریالیتی جواب بده .ممنون میشم



Sent from my Galaxy



-------- Original message --------
From: Nameles Ghoul ***@***.***>
Date: 5/19/23 18:14 (GMT+03:30)
To: namelesghoul/sing-box-REALITY ***@***.***>
Cc: shahrokh451 ***@***.***>, Author ***@***.***>
Subject: Re: [namelesghoul/sing-box-REALITY] uninstal (Issue #3)


Closed #3<https://github.com/namelesghoul/sing-box-REALITY/issues/3> as completed.
