### ISSUE TITLE
ایراد در تغییر sni؟

### ISSUE THREAD

**Issue by alighaffari3000** [namelesghoul/sing-box-REALITY#4]
سلام. 
بعد از اینکه با Modify میاییم sni رو تغییر میدیم تو فایل reality.jason فقط پارامتر server_name تغییر میکنه و پارامتر server رو همون قبلی میمونه! آیا این یک ایراده؟
![Screenshot 2023-05-19 210839](https://github.com/namelesghoul/sing-box-REALITY/assets/41757428/ae42c0c4-d5a2-495a-a653-447474be665c)

**Comment by namelesghoul** [comment]
بله . در کد باگی وجود داشت که برطرف شد . از آخرین نسخه منتشر شده استفاده کنید. همچنین قسمت modify الان پورت و sni فعلی رو هم بهتون نشون میده.
مرسی برای اطلاع رسانی
