### ISSUE TITLE
this script install sing-box version unknown

### ISSUE THREAD

**Issue by zhe1253** [namelesghoul/sing-box-REALITY#6]
-bash-5.0# sing-box version
sing-box version unknown

Environment: go1.20.3 linux/amd64
Tags: with_quic,with_grpc,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_v2ray_api,with_gvisor,with_lwip
CGO: enabled

**Comment by deathline94** [comment]
Discontinued ! follow up with the new releases in my other repo : https://github.com/deathline94/sing-REALITY-Box
